version = 1

test_patterns = ["test/**"]

exclude_patterns = ["/bin/"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"